[package]
name = "rust-parser"
version = "0.0.1"
authors = ["Luni-4 <luni-4@hotmail.it>"]
edition = "2018"

#[dependencies]
#tree-sitter-core = { git = "https://github.com/lu-zero/tree-sitter-core", branch = "parser" }

[profile.release]
opt-level = 3
debug = false
