
static mut ts_alias_sequences: [[TSSymbol; 10]; 234] = [
    [0 as libc::c_int as TSSymbol, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_primitive_type as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        sym_generic_type as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        sym_generic_type as libc::c_int as TSSymbol,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_shorthand_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        alias_sym_primitive_type as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_shorthand_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        0,
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        sym_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_shorthand_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        alias_sym_field_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [
        0,
        0,
        0,
        alias_sym_type_identifier as libc::c_int as TSSymbol,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
    [0; 10],
];
